# fly.toml app configuration file
app = 'tracker-proxy'
primary_region = 'ewr'

[build]
  dockerfile = 'Dockerfile'

[[services]]
  protocol = 'tcp'
  internal_port = 5001

  [[services.ports]]
    port = 5001

# Remove the TCP health check - it's interfering with connections

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
